In [73]:
import pandas as pd

In [74]:
df= pd.read_csv("Dataset1.csv")
df

    Length  Breath  Height  Classification
0       21      21      21               1
1       22      21      21               0
2       21      22      21               0
3       21      21      22               0
4       20      21      21               0
5       21      20      21               0
6       21      21      21               1
7       21      21      20               0
8       21      21      21               1
9       21      21      21               1
10      21      21      21               1
11      21      21      22               0
12      22      21      21               0
13      21      22      21               0
14      20      21      21               0
15      21      20      21               0
16      21      21      20               0
17      21      21      21               1
18      21      21      21               1
19      20      21      22               0
20      21      20      22               0
21      22      20      21               0
22      20      22      21               0
23      22      21      20               0
24      21      21      21               1

In [75]:
from sklearn.model_selection import train_test_split
X = df.drop('Classification',axis=1)
y = df.Classification
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2)
print(X)
print(y)

    Length  Breath  Height
0       21      21      21
1       22      21      21
2       21      22      21
3       21      21      22
4       20      21      21
5       21      20      21
6       21      21      21
7       21      21      20
8       21      21      21
9       21      21      21
10      21      21      21
11      21      21      22
12      22      21      21
13      21      22      21
14      20      21      21
15      21      20      21
16      21      21      20
17      21      21      21
18      21      21      21
19      20      21      22
20      21      20      22
21      22      20      21
22      20      22      21
23      22      21      20
24      21      21      21
0     1
1     0
2     0
3     0
4     0
5     0
6     1
7     0
8     1
9     1
10    1
11    0
12    0
13    0
14    0
15    0
16    0
17    1
18    1
19    0
20    0
21    0
22    0
23    0
24    1
Name: Classification, dtype: int64

In [76]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier( max_features = 3)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
y_pred

array([1, 1, 1, 0, 0], dtype=int64)

In [77]:
from sklearn.metrics import accuracy_score
rf_acc = accuracy_score(y_test, y_pred)
print("accuracy_score: ", rf_acc)

accuracy_score:  1.0

In [78]:
rf_train_score = rf.score(X_train, y_train)
rf_test_score= rf.score(X_test, y_test)
print(rf_train_score,rf_test_score)

1.0 1.0

In [103]:
classification=rf.predict([[21,21,21]])
classification[0]

1